SECTION21_FULL_SCHEMA = {
    "type": "object",
    "properties": {
        "section": {
            "type": "string",
            "enum": ["estate_planning_final_wishes"],
        },
        "scope": {
            "type": "string",
            "enum": ["section", "subsection"],
        },
        "subsection": {
            "type": ["string", "null"],
            "enum": [None, "21A", "21B", "21C"],
        },
        "confidence": {
            "type": "number",
        },
        "patch": {
            "type": "object",
            "properties": {
                "21A": {
                    "type": "object",
                    "properties": {
                        "will_location": {"type": ["string", "null"]},
                        "will_date": {"type": ["string", "null"]},
                        "executor_info": {"type": ["string", "null"]},
                        "alternate_executor": {"type": ["string", "null"]},
                        "will_attorney": {"type": ["string", "null"]},
                        "trust_info": {"type": ["string", "null"]},
                        "trustee_info": {"type": ["string", "null"]},
                        "successor_trustee": {"type": ["string", "null"]},
                        "trust_attorney": {"type": ["string", "null"]},
                        "financial_poa": {"type": ["string", "null"]},
                        "medical_poa": {"type": ["string", "null"]},
                        "living_will": {"type": ["string", "null"]},
                        "dnr_orders": {"type": ["string", "null"]},
                        "organ_donation": {"type": ["string", "null"]},
                        "primary_beneficiaries": {"type": ["string", "null"]},
                        "contingent_beneficiaries": {"type": ["string", "null"]},
                        "special_bequests": {"type": ["string", "null"]},
                        "charitable_bequests": {"type": ["string", "null"]},
                    },
                    "additionalProperties": False,
                },
                "21B": {
                    "type": "object",
                    "properties": {
                        "funeral_type": {"type": ["string", "null"]},
                        "funeral_type_other": {"type": ["string", "null"]},
                        "service_location": {"type": ["string", "null"]},
                        "funeral_home": {"type": ["string", "null"]},
                        "clergy_officiant": {"type": ["string", "null"]},
                        "service_preferences": {"type": ["string", "null"]},
                        "disposition_type": {"type": ["string", "null"]},
                        "disposition_type_other": {"type": ["string", "null"]},
                        "burial_location": {"type": ["string", "null"]},
                        "cremation_preferences": {"type": ["string", "null"]},
                        "body_donation_info": {"type": ["string", "null"]},
                        "headstone_marker": {"type": ["string", "null"]},
                        "memorial_donations": {"type": ["string", "null"]},
                        "special_requests": {"type": ["string", "null"]},
                        "obituary_details": {"type": ["string", "null"]},
                        "photo_for_obituary": {"type": ["string", "null"]},
                        "prepaid_funeral": {"type": ["string", "null"]},
                        "cemetery_plot": {"type": ["string", "null"]},
                        "funeral_insurance": {"type": ["string", "null"]},
                    },
                    "additionalProperties": False,
                },
                "21C": {
                    "type": "object",
                    "properties": {
                        "minor_children_info": {"type": ["string", "null"]},
                        "primary_guardian_name": {"type": ["string", "null"]},
                        "primary_guardian_relationship": {"type": ["string", "null"]},
                        "primary_guardian_contact": {"type": ["string", "null"]},
                        "primary_guardian_consent": {"type": ["string", "null"]},
                        "alternate_guardian_name": {"type": ["string", "null"]},
                        "alternate_guardian_relationship": {"type": ["string", "null"]},
                        "alternate_guardian_contact": {"type": ["string", "null"]},
                        "alternate_guardian_consent": {"type": ["string", "null"]},
                        "parenting_philosophy": {"type": ["string", "null"]},
                        "education_preferences": {"type": ["string", "null"]},
                        "religious_preferences": {"type": ["string", "null"]},
                        "healthcare_instructions": {"type": ["string", "null"]},
                        "special_needs": {"type": ["string", "null"]},
                        "extracurricular_activities": {"type": ["string", "null"]},
                        "relationship_maintenance": {"type": ["string", "null"]},
                        "trust_arrangements": {"type": ["string", "null"]},
                        "life_insurance": {"type": ["string", "null"]},
                        "education_funding": {"type": ["string", "null"]},
                        "guardian_compensation": {"type": ["string", "null"]},
                        "guardianship_will": {"type": ["string", "null"]},
                        "guardian_letters": {"type": ["string", "null"]},
                        "custody_agreements": {"type": ["string", "null"]},
                        "guardianship_attorney": {"type": ["string", "null"]},
                        "excluded_persons": {"type": ["string", "null"]},
                        "temporary_caregivers": {"type": ["string", "null"]},
                        "school_contacts": {"type": ["string", "null"]},
                        "medical_contacts": {"type": ["string", "null"]},
                    },
                    "additionalProperties": False,
                },
            },
            "additionalProperties": False,
        },
    },
    "required": ["section", "scope", "subsection", "confidence", "patch"],
    "additionalProperties": False,
}