SECTION1_FULL_SCHEMA = {
    "type": "object",
    "properties": {
        "section": {
            "type": "string",
            "enum": ["vital_information"],
        },
        "scope": {
            "type": "string",
            "enum": ["section", "subsection"],
        },
        "subsection": {
            "type": ["string", "null"],
            "enum": [
                None,
                "vital_info",
                "next_of_kin",
                "executor_trustee",
                "additional_contacts",
            ],
        },
        "confidence": {
            "type": "number",
        },
        "patch": {
            "type": "object",
            "properties": {
                "vital_info": {
                    "type": "object",
                    "properties": {
                        "full_legal_name": {"type": ["string", "null"]},
                        "other_names": {"type": ["string", "null"]},
                        "date_of_birth": {"type": ["string", "null"]},
                        "social_security_number": {"type": ["string", "null"]},
                        "drivers_license_number": {"type": ["string", "null"]},
                        "drivers_license_dd_number": {"type": ["string", "null"]},
                        "drivers_license_class": {"type": ["string", "null"]},
                        "drivers_license_issue_date": {"type": ["string", "null"]},
                        "drivers_license_expiration_date": {"type": ["string", "null"]},
                        "phone_number": {"type": ["string", "null"]},
                        "phone_password": {"type": ["string", "null"]},
                        "voicemail_pin": {"type": ["string", "null"]},
                        "computer_password": {"type": ["string", "null"]},
                        "primary_email_username": {"type": ["string", "null"]},
                        "primary_email_password": {"type": ["string", "null"]},
                        "secondary_email_username": {"type": ["string", "null"]},
                        "secondary_email_password": {"type": ["string", "null"]},
                        "safe_code": {"type": ["string", "null"]},
                        "safe_location": {"type": ["string", "null"]},
                        "safe_keys": {"type": ["string", "null"]},
                        "google_id_username": {"type": ["string", "null"]},
                        "google_id_password": {"type": ["string", "null"]},
                        "apple_id_username": {"type": ["string", "null"]},
                        "apple_id_password": {"type": ["string", "null"]},
                        "security_question_answers": {"type": ["string", "null"]},
                        "frequent_pins": {"type": ["string", "null"]},
                    },
                    "additionalProperties": False,
                },
                "next_of_kin": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "contact_name": {"type": ["string", "null"]},
                            "relationship": {"type": ["string", "null"]},
                            "phone_number": {"type": ["string", "null"]},
                            "email_address": {"type": ["string", "null"]},
                            "mailing_address": {"type": ["string", "null"]},
                            "alternate_contact": {"type": ["string", "null"]},
                            "priority_level": {"type": ["string", "null"]},
                            "special_instructions": {"type": ["string", "null"]},
                        },
                        "additionalProperties": False,
                    },
                },
                "executor_trustee": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "contact_name": {"type": ["string", "null"]},
                            "role_title": {"type": ["string", "null"]},
                            "relationship": {"type": ["string", "null"]},
                            "phone_number": {"type": ["string", "null"]},
                            "email_address": {"type": ["string", "null"]},
                            "company_organization": {"type": ["string", "null"]},
                            "mailing_address": {"type": ["string", "null"]},
                            "services_provided": {"type": ["string", "null"]},
                            "special_instructions": {"type": ["string", "null"]},
                            "contact_documents": {"type": ["string", "null"]},
                        },
                        "additionalProperties": False,
                    },
                },
                "additional_contacts": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "contact_name": {"type": ["string", "null"]},
                            "role_title": {"type": ["string", "null"]},
                            "relationship": {"type": ["string", "null"]},
                            "phone_number": {"type": ["string", "null"]},
                            "email_address": {"type": ["string", "null"]},
                            "company_organization": {"type": ["string", "null"]},
                            "mailing_address": {"type": ["string", "null"]},
                            "priority_level": {"type": ["string", "null"]},
                            "services_provided": {"type": ["string", "null"]},
                            "special_instructions": {"type": ["string", "null"]},
                            "contact_documents": {"type": ["string", "null"]},
                        },
                        "additionalProperties": False,
                    },
                },
            },
            "additionalProperties": False,
        },
    },
    "required": ["section", "scope", "subsection", "confidence", "patch"],
    "additionalProperties": False,
}